package adobe

// baseSpeechVoices 是从 cn.bing.com_2026_05_07_17_28_43.har 里直接拷贝出来的 328 条
// speechSynthesis.getVoices() 真机输出（Edge 143 Win11）。
//
// Adobe BFP 后端会用这份列表估计 numVoices/语音多样性，过短/全英会被怀疑。
// 整份列表 ~21 KB，让 BFP payload 接近真机的 27 KB 量级，避免被"单一指纹"启发式打掉。
var baseSpeechVoices = []string{
	"Microsoft Huihui - Chinese (Simplified, PRC) zh-CN",
	"Microsoft Mark - English (United States) en-US",
	"Microsoft Zira - English (United States) en-US",
	"Microsoft David - English (United States) en-US",
	"Microsoft Kangkang - Chinese (Simplified, PRC) zh-CN",
	"Microsoft Yaoyao - Chinese (Simplified, PRC) zh-CN",
	"Microsoft Adri Online (Natural) - Afrikaans (South Africa) af-ZA",
	"Microsoft Willem Online (Natural) - Afrikaans (South Africa) af-ZA",
	"Microsoft Anila Online (Natural) - Albanian (Albania) sq-AL",
	"Microsoft Ilir Online (Natural) - Albanian (Albania) sq-AL",
	"Microsoft Ameha Online (Natural) - Amharic (Ethiopia) am-ET",
	"Microsoft Mekdes Online (Natural) - Amharic (Ethiopia) am-ET",
	"Microsoft Amina Online (Natural) - Arabic (Algeria) ar-DZ",
	"Microsoft Ismael Online (Natural) - Arabic (Algeria) ar-DZ",
	"Microsoft Ali Online (Natural) - Arabic (Bahrain) ar-BH",
	"Microsoft Laila Online (Natural) - Arabic (Bahrain) ar-BH",
	"Microsoft Salma Online (Natural) - Arabic (Egypt) ar-EG",
	"Microsoft Shakir Online (Natural) - Arabic (Egypt) ar-EG",
	"Microsoft Bassel Online (Natural) - Arabic (Iraq) ar-IQ",
	"Microsoft Rana Online (Natural) - Arabic (Iraq) ar-IQ",
	"Microsoft Sana Online (Natural) - Arabic (Jordan) ar-JO",
	"Microsoft Taim Online (Natural) - Arabic (Jordan) ar-JO",
	"Microsoft Fahed Online (Natural) - Arabic (Kuwait) ar-KW",
	"Microsoft Noura Online (Natural) - Arabic (Kuwait) ar-KW",
	"Microsoft Layla Online (Natural) - Arabic (Lebanon) ar-LB",
	"Microsoft Rami Online (Natural) - Arabic (Lebanon) ar-LB",
	"Microsoft Iman Online (Natural) - Arabic (Libya) ar-LY",
	"Microsoft Omar Online (Natural) - Arabic (Libya) ar-LY",
	"Microsoft Jamal Online (Natural) - Arabic (Morocco) ar-MA",
	"Microsoft Mouna Online (Natural) - Arabic (Morocco) ar-MA",
	"Microsoft Abdullah Online (Natural) - Arabic (Oman) ar-OM",
	"Microsoft Aysha Online (Natural) - Arabic (Oman) ar-OM",
	"Microsoft Amal Online (Natural) - Arabic (Qatar) ar-QA",
	"Microsoft Moaz Online (Natural) - Arabic (Qatar) ar-QA",
	"Microsoft Hamed Online (Natural) - Arabic (Saudi Arabia) ar-SA",
	"Microsoft Zariyah Online (Natural) - Arabic (Saudi Arabia) ar-SA",
	"Microsoft Amany Online (Natural) - Arabic (Syria) ar-SY",
	"Microsoft Laith Online (Natural) - Arabic (Syria) ar-SY",
	"Microsoft Hedi Online (Natural) - Arabic (Tunisia) ar-TN",
	"Microsoft Reem Online (Natural) - Arabic (Tunisia) ar-TN",
	"Microsoft Fatima Online (Natural) - Arabic (United Arab Emirates) ar-AE",
	"Microsoft Hamdan Online (Natural) - Arabic (United Arab Emirates) ar-AE",
	"Microsoft Maryam Online (Natural) - Arabic (Yemen) ar-YE",
	"Microsoft Saleh Online (Natural) - Arabic (Yemen) ar-YE",
	"Microsoft Babek Online (Natural) - Azerbaijani (Azerbaijan) az-AZ",
	"Microsoft Banu Online (Natural) - Azerbaijani (Azerbaijan) az-AZ",
	"Microsoft Nabanita Online (Natural) - Bangla (Bangladesh) bn-BD",
	"Microsoft Pradeep Online (Natural) - Bangla (Bangladesh) bn-BD",
	"Microsoft Bashkar Online (Natural) - Bangla (India) bn-IN",
	"Microsoft Tanishaa Online (Natural) - Bengali (India) bn-IN",
	"Microsoft Vesna Online (Natural) - Bosnian (Bosnia and Herzegovina) bs-BA",
	"Microsoft Goran Online (Natural) - Bosnian (Bosnia) bs-BA",
	"Microsoft Borislav Online (Natural) - Bulgarian (Bulgaria) bg-BG",
	"Microsoft Kalina Online (Natural) - Bulgarian (Bulgaria) bg-BG",
	"Microsoft Nilar Online (Natural) - Burmese (Myanmar) my-MM",
	"Microsoft Thiha Online (Natural) - Burmese (Myanmar) my-MM",
	"Microsoft Enric Online (Natural) - Catalan ca-ES",
	"Microsoft Joana Online (Natural) - Catalan ca-ES",
	"Microsoft HiuGaai Online (Natural) - Chinese (Cantonese Traditional) zh-HK",
	"Microsoft HiuMaan Online (Natural) - Chinese (Hong Kong SAR) zh-HK",
	"Microsoft WanLung Online (Natural) - Chinese (Hong Kong SAR) zh-HK",
	"Microsoft Xiaoxiao Online (Natural) - Chinese (Mainland) zh-CN",
	"Microsoft Xiaoyi Online (Natural) - Chinese (Mainland) zh-CN",
	"Microsoft Yunjian Online (Natural) - Chinese (Mainland) zh-CN",
	"Microsoft Yunxi Online (Natural) - Chinese (Mainland) zh-CN",
	"Microsoft Yunxia Online (Natural) - Chinese (Mainland) zh-CN",
	"Microsoft Yunyang Online (Natural) - Chinese (Mainland) zh-CN",
	"Microsoft Xiaobei Online (Natural) - Chinese (Northeastern Mandarin) zh-CN-liaoning",
	"Microsoft HsiaoChen Online (Natural) - Chinese (Taiwan) zh-TW",
	"Microsoft YunJhe Online (Natural) - Chinese (Taiwan) zh-TW",
	"Microsoft HsiaoYu Online (Natural) - Chinese (Taiwanese Mandarin) zh-TW",
	"Microsoft Xiaoni Online (Natural) - Chinese (Zhongyuan Mandarin Shaanxi) zh-CN-shaanxi",
	"Microsoft Gabrijela Online (Natural) - Croatian (Croatia) hr-HR",
	"Microsoft Srecko Online (Natural) - Croatian (Croatia) hr-HR",
	"Microsoft Antonin Online (Natural) - Czech (Czech) cs-CZ",
	"Microsoft Vlasta Online (Natural) - Czech (Czech) cs-CZ",
	"Microsoft Christel Online (Natural) - Danish (Denmark) da-DK",
	"Microsoft Jeppe Online (Natural) - Danish (Denmark) da-DK",
	"Microsoft Arnaud Online (Natural) - Dutch (Belgium) nl-BE",
	"Microsoft Dena Online (Natural) - Dutch (Belgium) nl-BE",
	"Microsoft Colette Online (Natural) - Dutch (Netherlands) nl-NL",
	"Microsoft Fenna Online (Natural) - Dutch (Netherlands) nl-NL",
	"Microsoft Maarten Online (Natural) - Dutch (Netherlands) nl-NL",
	"Microsoft WilliamMultilingual Online (Natural) - English (Australia) en-AU",
	"Microsoft Natasha Online (Natural) - English (Australia) en-AU",
	"Microsoft Clara Online (Natural) - English (Canada) en-CA",
	"Microsoft Liam Online (Natural) - English (Canada) en-CA",
	"Microsoft Yan Online (Natural) - English (Hong Kong SAR) en-HK",
	"Microsoft Sam Online (Natural) - English (Hongkong) en-HK",
	"Microsoft Neerja Online (Natural) - English (India) (Preview) en-IN",
	"Microsoft Neerja Online (Natural) - English (India) en-IN",
	"Microsoft Prabhat Online (Natural) - English (India) en-IN",
	"Microsoft Connor Online (Natural) - English (Ireland) en-IE",
	"Microsoft Emily Online (Natural) - English (Ireland) en-IE",
	"Microsoft Asilia Online (Natural) - English (Kenya) en-KE",
	"Microsoft Chilemba Online (Natural) - English (Kenya) en-KE",
	"Microsoft Mitchell Online (Natural) - English (New Zealand) en-NZ",
	"Microsoft Molly Online (Natural) - English (New Zealand) en-NZ",
	"Microsoft Abeo Online (Natural) - English (Nigeria) en-NG",
	"Microsoft Ezinne Online (Natural) - English (Nigeria) en-NG",
	"Microsoft James Online (Natural) - English (Philippines) en-PH",
	"Microsoft Rosa Online (Natural) - English (Philippines) en-PH",
	"Microsoft Ava Online (Natural) - English (United States) en-US",
	"Microsoft Andrew Online (Natural) - English (United States) en-US",
	"Microsoft Emma Online (Natural) - English (United States) en-US",
	"Microsoft Brian Online (Natural) - English (United States) en-US",
	"Microsoft Luna Online (Natural) - English (Singapore) en-SG",
	"Microsoft Wayne Online (Natural) - English (Singapore) en-SG",
	"Microsoft Leah Online (Natural) - English (South Africa) en-ZA",
	"Microsoft Luke Online (Natural) - English (South Africa) en-ZA",
	"Microsoft Elimu Online (Natural) - English (Tanzania) en-TZ",
	"Microsoft Imani Online (Natural) - English (Tanzania) en-TZ",
	"Microsoft Libby Online (Natural) - English (United Kingdom) en-GB",
	"Microsoft Maisie Online (Natural) - English (United Kingdom) en-GB",
	"Microsoft Ryan Online (Natural) - English (United Kingdom) en-GB",
	"Microsoft Sonia Online (Natural) - English (United Kingdom) en-GB",
	"Microsoft Thomas Online (Natural) - English (United Kingdom) en-GB",
	"Microsoft Ana Online (Natural) - English (United States) en-US",
	"Microsoft AndrewMultilingual Online (Natural) - English (United States) en-US",
	"Microsoft Aria Online (Natural) - English (United States) en-US",
	"Microsoft AvaMultilingual Online (Natural) - English (United States) en-US",
	"Microsoft BrianMultilingual Online (Natural) - English (United States) en-US",
	"Microsoft Christopher Online (Natural) - English (United States) en-US",
	"Microsoft EmmaMultilingual Online (Natural) - English (United States) en-US",
	"Microsoft Eric Online (Natural) - English (United States) en-US",
	"Microsoft Guy Online (Natural) - English (United States) en-US",
	"Microsoft Jenny Online (Natural) - English (United States) en-US",
	"Microsoft Michelle Online (Natural) - English (United States) en-US",
	"Microsoft Roger Online (Natural) - English (United States) en-US",
	"Microsoft Steffan Online (Natural) - English (United States) en-US",
	"Microsoft Anu Online (Natural) - Estonian (Estonia) et-EE",
	"Microsoft Kert Online (Natural) - Estonian (Estonia) et-EE",
	"Microsoft Angelo Online (Natural) - Filipino (Philippines) fil-PH",
	"Microsoft Blessica Online (Natural) - Filipino (Philippines) fil-PH",
	"Microsoft Harri Online (Natural) - Finnish (Finland) fi-FI",
	"Microsoft Noora Online (Natural) - Finnish (Finland) fi-FI",
	"Microsoft Charline Online (Natural) - French (Belgium) fr-BE",
	"Microsoft Gerard Online (Natural) - French (Belgium) fr-BE",
	"Microsoft Thierry Online (Natural) - French (Canada) fr-CA",
	"Microsoft Antoine Online (Natural) - French (Canada) fr-CA",
	"Microsoft Jean Online (Natural) - French (Canada) fr-CA",
	"Microsoft Sylvie Online (Natural) - French (Canada) fr-CA",
	"Microsoft VivienneMultilingual Online (Natural) - French (France) fr-FR",
	"Microsoft RemyMultilingual Online (Natural) - French (France) fr-FR",
	"Microsoft Denise Online (Natural) - French (France) fr-FR",
	"Microsoft Eloise Online (Natural) - French (France) fr-FR",
	"Microsoft Henri Online (Natural) - French (France) fr-FR",
	"Microsoft Ariane Online (Natural) - French (Switzerland) fr-CH",
	"Microsoft Fabrice Online (Natural) - French (Switzerland) fr-CH",
	"Microsoft Roi Online (Natural) - Galician gl-ES",
	"Microsoft Sabela Online (Natural) - Galician gl-ES",
	"Microsoft Eka Online (Natural) - Georgian (Georgia) ka-GE",
	"Microsoft Giorgi Online (Natural) - Georgian (Georgia) ka-GE",
	"Microsoft Ingrid Online (Natural) - German (Austria) de-AT",
	"Microsoft Jonas Online (Natural) - German (Austria) de-AT",
	"Microsoft SeraphinaMultilingual Online (Natural) - German (Germany) de-DE",
	"Microsoft FlorianMultilingual Online (Natural) - German (Germany) de-DE",
	"Microsoft Amala Online (Natural) - German (Germany) de-DE",
	"Microsoft Conrad Online (Natural) - German (Germany) de-DE",
	"Microsoft Katja Online (Natural) - German (Germany) de-DE",
	"Microsoft Killian Online (Natural) - German (Germany) de-DE",
	"Microsoft Jan Online (Natural) - German (Switzerland) de-CH",
	"Microsoft Leni Online (Natural) - German (Switzerland) de-CH",
	"Microsoft Athina Online (Natural) - Greek (Greece) el-GR",
	"Microsoft Nestoras Online (Natural) - Greek (Greece) el-GR",
	"Microsoft Dhwani Online (Natural) - Gujarati (India) gu-IN",
	"Microsoft Niranjan Online (Natural) - Gujarati (India) gu-IN",
	"Microsoft Avri Online (Natural) - Hebrew (Israel) he-IL",
	"Microsoft Hila Online (Natural) - Hebrew (Israel) he-IL",
	"Microsoft Madhur Online (Natural) - Hindi (India) hi-IN",
	"Microsoft Swara Online (Natural) - Hindi (India) hi-IN",
	"Microsoft Noemi Online (Natural) - Hungarian (Hungary) hu-HU",
	"Microsoft Tamas Online (Natural) - Hungarian (Hungary) hu-HU",
	"Microsoft Gudrun Online (Natural) - Icelandic (Iceland) is-IS",
	"Microsoft Gunnar Online (Natural) - Icelandic (Iceland) is-IS",
	"Microsoft Ardi Online (Natural) - Indonesian (Indonesia) id-ID",
	"Microsoft Gadis Online (Natural) - Indonesian (Indonesia) id-ID",
	"Microsoft Siqiniq Online (Natural) - Inuktitut (Latin, Canada) iu-Latn-CA",
	"Microsoft Taqqiq Online (Natural) - Inuktitut (Latin, Canada) iu-Latn-CA",
	"Microsoft Siqiniq Online (Natural) - Inuktitut (Syllabics, Canada) iu-Cans-CA",
	"Microsoft Taqqiq Online (Natural) - Inuktitut (Syllabics, Canada) iu-Cans-CA",
	"Microsoft Colm Online (Natural) - Irish (Ireland) ga-IE",
	"Microsoft Orla Online (Natural) - Irish (Ireland) ga-IE",
	"Microsoft GiuseppeMultilingual Online (Natural) - Italian (Italy) it-IT",
	"Microsoft Diego Online (Natural) - Italian (Italy) it-IT",
	"Microsoft Elsa Online (Natural) - Italian (Italy) it-IT",
	"Microsoft Isabella Online (Natural) - Italian (Italy) it-IT",
	"Microsoft Keita Online (Natural) - Japanese (Japan) ja-JP",
	"Microsoft Nanami Online (Natural) - Japanese (Japan) ja-JP",
	"Microsoft Dimas Online (Natural) - Javanese (Indonesia) jv-ID",
	"Microsoft Siti Online (Natural) - Javanese (Indonesia) jv-ID",
	"Microsoft Gagan Online (Natural) - Kannada (India) kn-IN",
	"Microsoft Sapna Online (Natural) - Kannada (India) kn-IN",
	"Microsoft Aigul Online (Natural) - Kazakh (Kazakhstan) kk-KZ",
	"Microsoft Daulet Online (Natural) - Kazakh (Kazakhstan) kk-KZ",
	"Microsoft Piseth Online (Natural) - Khmer (Cambodia) km-KH",
	"Microsoft Sreymom Online (Natural) - Khmer (Cambodia) km-KH",
	"Microsoft HyunsuMultilingual Online (Natural) - Korean (Korea) ko-KR",
	"Microsoft InJoon Online (Natural) - Korean (Korea) ko-KR",
	"Microsoft SunHi Online (Natural) - Korean (Korea) ko-KR",
	"Microsoft Chanthavong Online (Natural) - Lao (Laos) lo-LA",
	"Microsoft Keomany Online (Natural) - Lao (Laos) lo-LA",
	"Microsoft Everita Online (Natural) - Latvian (Latvia) lv-LV",
	"Microsoft Nils Online (Natural) - Latvian (Latvia) lv-LV",
	"Microsoft Leonas Online (Natural) - Lithuanian (Lithuania) lt-LT",
	"Microsoft Ona Online (Natural) - Lithuanian (Lithuania) lt-LT",
	"Microsoft Aleksandar Online (Natural) - Macedonian (North Macedonia) mk-MK",
	"Microsoft Marija Online (Natural) - Macedonian (North Macedonia) mk-MK",
	"Microsoft Osman Online (Natural) - Malay (Malaysia) ms-MY",
	"Microsoft Yasmin Online (Natural) - Malay (Malaysia) ms-MY",
	"Microsoft Midhun Online (Natural) - Malayalam (India) ml-IN",
	"Microsoft Sobhana Online (Natural) - Malayalam (India) ml-IN",
	"Microsoft Grace Online (Natural) - Maltese (Malta) mt-MT",
	"Microsoft Joseph Online (Natural) - Maltese (Malta) mt-MT",
	"Microsoft Aarohi Online (Natural) - Marathi (India) mr-IN",
	"Microsoft Manohar Online (Natural) - Marathi (India) mr-IN",
	"Microsoft Bataa Online (Natural) - Mongolian (Mongolia) mn-MN",
	"Microsoft Yesui Online (Natural) - Mongolian (Mongolia) mn-MN",
	"Microsoft Hemkala Online (Natural) - Nepali (Nepal) ne-NP",
	"Microsoft Sagar Online (Natural) - Nepali (Nepal) ne-NP",
	"Microsoft Finn Online (Natural) - Norwegian (Bokmål Norway) nb-NO",
	"Microsoft Pernille Online (Natural) - Norwegian (Bokmål, Norway) nb-NO",
	"Microsoft GulNawaz Online (Natural) - Pashto (Afghanistan) ps-AF",
	"Microsoft Latifa Online (Natural) - Pashto (Afghanistan) ps-AF",
	"Microsoft Dilara Online (Natural) - Persian (Iran) fa-IR",
	"Microsoft Farid Online (Natural) - Persian (Iran) fa-IR",
	"Microsoft Marek Online (Natural) - Polish (Poland) pl-PL",
	"Microsoft Zofia Online (Natural) - Polish (Poland) pl-PL",
	"Microsoft ThalitaMultilingual Online (Natural) - Portuguese (Brazil) pt-BR",
	"Microsoft Antonio Online (Natural) - Portuguese (Brazil) pt-BR",
	"Microsoft Francisca Online (Natural) - Portuguese (Brazil) pt-BR",
	"Microsoft Duarte Online (Natural) - Portuguese (Portugal) pt-PT",
	"Microsoft Raquel Online (Natural) - Portuguese (Portugal) pt-PT",
	"Microsoft Alina Online (Natural) - Romanian (Romania) ro-RO",
	"Microsoft Emil Online (Natural) - Romanian (Romania) ro-RO",
	"Microsoft Dmitry Online (Natural) - Russian (Russia) ru-RU",
	"Microsoft Svetlana Online (Natural) - Russian (Russia) ru-RU",
	"Microsoft Nicholas Online (Natural) - Serbian (Serbia) sr-RS",
	"Microsoft Sophie Online (Natural) - Serbian (Serbia) sr-RS",
	"Microsoft Sameera Online (Natural) - Sinhala (Sri Lanka) si-LK",
	"Microsoft Thilini Online (Natural) - Sinhala (Sri Lanka) si-LK",
	"Microsoft Lukas Online (Natural) - Slovak (Slovakia) sk-SK",
	"Microsoft Viktoria Online (Natural) - Slovak (Slovakia) sk-SK",
	"Microsoft Petra Online (Natural) - Slovenian (Slovenia) sl-SI",
	"Microsoft Rok Online (Natural) - Slovenian (Slovenia) sl-SI",
	"Microsoft Muuse Online (Natural) - Somali (Somalia) so-SO",
	"Microsoft Ubax Online (Natural) - Somali (Somalia) so-SO",
	"Microsoft Elena Online (Natural) - Spanish (Argentina) es-AR",
	"Microsoft Tomas Online (Natural) - Spanish (Argentina) es-AR",
	"Microsoft Marcelo Online (Natural) - Spanish (Bolivia) es-BO",
	"Microsoft Sofia Online (Natural) - Spanish (Bolivia) es-BO",
	"Microsoft Catalina Online (Natural) - Spanish (Chile) es-CL",
	"Microsoft Lorenzo Online (Natural) - Spanish (Chile) es-CL",
	"Microsoft Gonzalo Online (Natural) - Spanish (Colombia) es-CO",
	"Microsoft Salome Online (Natural) - Spanish (Colombia) es-CO",
	"Microsoft Ximena Online (Natural) - Spanish (Colombia) es-ES",
	"Microsoft Juan Online (Natural) - Spanish (Costa Rica) es-CR",
	"Microsoft Maria Online (Natural) - Spanish (Costa Rica) es-CR",
	"Microsoft Belkys Online (Natural) - Spanish (Cuba) es-CU",
	"Microsoft Manuel Online (Natural) - Spanish (Cuba) es-CU",
	"Microsoft Emilio Online (Natural) - Spanish (Dominican Republic) es-DO",
	"Microsoft Ramona Online (Natural) - Spanish (Dominican Republic) es-DO",
	"Microsoft Andrea Online (Natural) - Spanish (Ecuador) es-EC",
	"Microsoft Luis Online (Natural) - Spanish (Ecuador) es-EC",
	"Microsoft Lorena Online (Natural) - Spanish (El Salvador) es-SV",
	"Microsoft Rodrigo Online (Natural) - Spanish (El Salvador) es-SV",
	"Microsoft Javier Online (Natural) - Spanish (Equatorial Guinea) es-GQ",
	"Microsoft Teresa Online (Natural) - Spanish (Equatorial Guinea) es-GQ",
	"Microsoft Andres Online (Natural) - Spanish (Guatemala) es-GT",
	"Microsoft Marta Online (Natural) - Spanish (Guatemala) es-GT",
	"Microsoft Carlos Online (Natural) - Spanish (Honduras) es-HN",
	"Microsoft Karla Online (Natural) - Spanish (Honduras) es-HN",
	"Microsoft Dalia Online (Natural) - Spanish (Mexico) es-MX",
	"Microsoft Jorge Online (Natural) - Spanish (Mexico) es-MX",
	"Microsoft Federico Online (Natural) - Spanish (Nicaragua) es-NI",
	"Microsoft Yolanda Online (Natural) - Spanish (Nicaragua) es-NI",
	"Microsoft Margarita Online (Natural) - Spanish (Panama) es-PA",
	"Microsoft Roberto Online (Natural) - Spanish (Panama) es-PA",
	"Microsoft Mario Online (Natural) - Spanish (Paraguay) es-PY",
	"Microsoft Tania Online (Natural) - Spanish (Paraguay) es-PY",
	"Microsoft Alex Online (Natural) - Spanish (Peru) es-PE",
	"Microsoft Camila Online (Natural) - Spanish (Peru) es-PE",
	"Microsoft Karina Online (Natural) - Spanish (Puerto Rico) es-PR",
	"Microsoft Victor Online (Natural) - Spanish (Puerto Rico) es-PR",
	"Microsoft Alvaro Online (Natural) - Spanish (Spain) es-ES",
	"Microsoft Elvira Online (Natural) - Spanish (Spain) es-ES",
	"Microsoft Alonso Online (Natural) - Spanish (United States) es-US",
	"Microsoft Paloma Online (Natural) - Spanish (United States) es-US",
	"Microsoft Mateo Online (Natural) - Spanish (Uruguay) es-UY",
	"Microsoft Valentina Online (Natural) - Spanish (Uruguay) es-UY",
	"Microsoft Paola Online (Natural) - Spanish (Venezuela) es-VE",
	"Microsoft Sebastian Online (Natural) - Spanish (Venezuela) es-VE",
	"Microsoft Jajang Online (Natural) - Sundanese (Indonesia) su-ID",
	"Microsoft Tuti Online (Natural) - Sundanese (Indonesia) su-ID",
	"Microsoft Rafiki Online (Natural) - Swahili (Kenya) sw-KE",
	"Microsoft Zuri Online (Natural) - Swahili (Kenya) sw-KE",
	"Microsoft Daudi Online (Natural) - Swahili (Tanzania) sw-TZ",
	"Microsoft Rehema Online (Natural) - Swahili (Tanzania) sw-TZ",
	"Microsoft Mattias Online (Natural) - Swedish (Sweden) sv-SE",
	"Microsoft Sofie Online (Natural) - Swedish (Sweden) sv-SE",
	"Microsoft Pallavi Online (Natural) - Tamil (India) ta-IN",
	"Microsoft Valluvar Online (Natural) - Tamil (India) ta-IN",
	"Microsoft Kani Online (Natural) - Tamil (Malaysia) ta-MY",
	"Microsoft Surya Online (Natural) - Tamil (Malaysia) ta-MY",
	"Microsoft Anbu Online (Natural) - Tamil (Singapore) ta-SG",
	"Microsoft Venba Online (Natural) - Tamil (Singapore) ta-SG",
	"Microsoft Kumar Online (Natural) - Tamil (Sri Lanka) ta-LK",
	"Microsoft Saranya Online (Natural) - Tamil (Sri Lanka) ta-LK",
	"Microsoft Mohan Online (Natural) - Telugu (India) te-IN",
	"Microsoft Shruti Online (Natural) - Telugu (India) te-IN",
	"Microsoft Niwat Online (Natural) - Thai (Thailand) th-TH",
	"Microsoft Premwadee Online (Natural) - Thai (Thailand) th-TH",
	"Microsoft Emel Online (Natural) - Turkish (Turkey) tr-TR",
	"Microsoft Ahmet Online (Natural) - Turkish (Türkiye) tr-TR",
	"Microsoft Ostap Online (Natural) - Ukrainian (Ukraine) uk-UA",
	"Microsoft Polina Online (Natural) - Ukrainian (Ukraine) uk-UA",
	"Microsoft Gul Online (Natural) - Urdu (India) ur-IN",
	"Microsoft Salman Online (Natural) - Urdu (India) ur-IN",
	"Microsoft Asad Online (Natural) - Urdu (Pakistan) ur-PK",
	"Microsoft Uzma Online (Natural) - Urdu (Pakistan) ur-PK",
	"Microsoft Madina Online (Natural) - Uzbek (Uzbekistan) uz-UZ",
	"Microsoft Sardor Online (Natural) - Uzbek (Uzbekistan) uz-UZ",
	"Microsoft HoaiMy Online (Natural) - Vietnamese (Vietnam) vi-VN",
	"Microsoft NamMinh Online (Natural) - Vietnamese (Vietnam) vi-VN",
	"Microsoft Aled Online (Natural) - Welsh (United Kingdom) cy-GB",
	"Microsoft Nia Online (Natural) - Welsh (United Kingdom) cy-GB",
	"Microsoft Thando Online (Natural) - Zulu (South Africa) zu-ZA",
	"Microsoft Themba Online (Natural) - Zulu (South Africa) zu-ZA",
}
